### ISSUE TITLE
Nucleus Error: Connection

### ISSUE THREAD

**Issue by solomon-momo** [j3soon/omni-farm-isaac#2]
Hi, I want to ask about Nucleus setting.

Right now I can run job about `Built-in Tasks` and official task like `gpu.kit`
![image](https://github.com/user-attachments/assets/2271e683-b6b8-40d4-8e86-a719d8f1ce3e)

Here is I followed your steps 
```
./omnicli auth NAME PASS

cd thirdparty/omnicli
./omnicli copy "../../tasks/isaac-sim-simulation-example.py" "omniverse://$NUCLEUS_HOSTNAME/Projects/$FARM_USER/Isaac/4.1/Scripts/isaac-sim-simulation-example.py"
cd ../..
```
and steps below

![image](https://github.com/user-attachments/assets/f64d5c21-37d5-4a62-a20a-c77215f5f05d)
![image](https://github.com/user-attachments/assets/2c5d5b6b-23e3-4cc1-939e-a20e5367bd06)
![image](https://github.com/user-attachments/assets/65d0d937-03c7-48da-8adc-51deb526437f)
![image](https://github.com/user-attachments/assets/e667694d-3ac6-45e0-b700-11aaa664452c)
![image](https://github.com/user-attachments/assets/a1b51473-56ca-46eb-aaed-2ff0416a8263)
![image](https://github.com/user-attachments/assets/6177a9d5-5ff7-4265-826f-5d5482b4fa3e)
![image](https://github.com/user-attachments/assets/96798b27-8c16-4f1d-b779-5fd6129362b0)

Can you help me to solve this issue?

**Comment by j3soon** [comment]
I think it's due to cannot access Nucleus through `localhost` within the K8s pod.

To investigate this issue, I suggest following the [Developer Notes](https://github.com/j3soon/omni-farm-isaac?tab=readme-ov-file#developer-notes) section:

<img width="624" alt="{C3FB9788-EF00-44B6-99BC-9B7AE91908C4}" src="https://github.com/user-attachments/assets/bc4b792a-076e-4df2-83df-620eae65c7f6">

I believe you should change the `localhost` used in the K8s pod to the IP/hostname of your Nucleus server.

<hr>

As a side note, I appreciate your detailed issue report.

**Comment by solomon-momo** [comment]
Thanks. I can connect to Nucleus now!
